[workspace]
authors = ["Ahmad Bassam El Bizri <34858431+1ahmadbassam@users.noreply.github.com>"]
channels = ["https://conda.modular.com/mojo", "conda-forge"]
name = "mojo-serial"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "25.5.0"
